First commit
HULK0680204682/OOPLabs pull request #1
Opened 2023-02-27 16:42 UTC by HULK0680204682

2023-02-28 21:41 UTC, RuslanSlobodian requested changes

2023-02-28 21:41 UTC, RuslanSlobodian commented on lab1/lab1/src/Train_package/Train.java
> +    private String Destination;
Назви атрибутів в класі згідно стилю Java мають бути з маленької букви

2023-02-28 21:41 UTC, RuslanSlobodian commented on lab1/lab1/src/Train_package/Train.java
> +    {
Дотримуйся однакового стилю коду!
Відкриваючу фігурну дужку став відразу в рядку із назвою методу, тобто згідно Java-стилю, 
так як ти це робив у методах вище

2023-02-28 21:41 UTC, RuslanSlobodian commented on lab1/lab1/src/Train_package/Train.java
> +    private int ShippingTime;
Час відправлення поїзда краще зберігати у форматі часу за допомогою класу LocalTime з пакету  java.time.LocalTime

2023-02-28 21:41 UTC, RuslanSlobodian commented on lab1/lab1/src/Main_package/Main.java
> +//import java.io.Console;
Не зберігай в коміті непотрібного (закоментованого) коду

2023-02-28 21:41 UTC, RuslanSlobodian commented on lab1/lab1/src/Main_package/Main.java
> +        Main m = new Main();
я б дав назву об'єкту main, а не просто m.

2023-02-28 21:41 UTC, RuslanSlobodian commented on lab1/lab1/src/Main_package/Main.java
> +                    System.exit(1);
Чому тут відбувається вихід з програми із повідомлення про помилку?

2023-02-28 21:41 UTC, RuslanSlobodian commented on lab1/lab1/src/Main_package/Main.java
> +            Scanner s = new Scanner(System.in);
Для чого створювати новий об'єкт класу Scanner на кожній ітерацій циклу while?
Хіба не можна його створити один раз до початку циклу?

2023-02-28 21:41 UTC, RuslanSlobodian commented on lab1/lab1/src/Main_package/Main.java
> +            int operation = s.nextInt();
Після зчитування цілого числа в консолі залишається перехід на новий рядок, це після натиснення на Enter. Його потрібно відразу прочитати за допомогою методу nextLine().

2023-02-28 21:41 UTC, RuslanSlobodian commented on lab1/lab1/src/Main_package/Main.java
> +    public void oper2()
Незрозуміла назва методу

2023-02-28 21:41 UTC, RuslanSlobodian commented on lab1/lab1/src/Main_package/Main.java
> +        int option3 = scanner.nextInt();
забув про nextLine

2023-02-28 21:41 UTC, RuslanSlobodian commented on lab1/lab1/src/Main_package/Main.java
> +        int operation2 = s.nextInt();
nextLine()

2023-03-01 10:00 UTC, ShurikIT-0680204682 commented on lab1/lab1/src/Main_package/Main.java
> +        int option3 = scanner.nextInt();
Якщо я пропишу .nextLine то буде видавати помилку "Incompatible types. Found: 'java.lang.String', required: 'int'"

2023-03-01 12:20 UTC, RuslanSlobodian commented on lab1/lab1/src/Main_package/Main.java
> +        int option3 = scanner.nextInt();
Я не кажу заміняти виклик методу nextInt(), а добивити його після зчитування цілого числа, щоб зчитати і відкинути введений Enter:
...
int option3 = scanner.nextInt();
scanner.nextLine();
...

2023-03-01 13:17 UTC, HULK0680204682 commented on lab1/lab1/src/Main_package/Main.java
> +        int option3 = scanner.nextInt();
дякую перероблю

2023-03-01 15:18 UTC, HULK0680204682 commented on lab1/lab1/src/Train_package/Train.java
> +    private int ShippingTime;
Підкажіть як  використати Scanner для запису в  LocalTime, в голову тільки прийшло зробити 2 змінних і підставляти їх для гг:хх

2023-03-01 15:20 UTC, HULK0680204682 commented on lab1/lab1/src/Train_package/Train.java
> +    private int ShippingTime;
або зробити стрінг і підставляти перше числ ояк годину а друге як хвилину через двокрапку

2023-03-01 16:03 UTC, HULK0680204682 commented on lab1/lab1/src/Train_package/Train.java
> +    private int ShippingTime;
типу 
int shippingTime1 = scanner.nextInt();
        int shippingTime2 = scanner.nextInt();
        LocalTime shippingTime = LocalTime.of(shippingTime1, shippingTime2);

        або

        //String shippingTime1 = new String();
        String shippingTime1 = scanner.nextLine();
        String[] parts = shippingTime1.split(":");
        String time1 = parts[0];
        String time2 = parts[1];
        timeHour = Integer.parseInt(time1);
        timeMinute = Integer.parseInt(time2);
        LocalTime shippingTime = LocalTime.of(timeHour , timeMinute );

2023-03-01 19:39 UTC, RuslanSlobodian commented on lab1/lab1/src/Train_package/Train.java
> +    private int ShippingTime;
https://www.geeksforgeeks.org/localdate-parse-method-in-java-with-examples/

2023-03-09 11:43 UTC, RuslanSlobodian requested changes

2023-03-09 11:43 UTC, RuslanSlobodian commented on lab1/lab1/src/Main_package/Main.java
> +        String SeaDes = SearchDestination();
SeaDes - не зрозуміла назва

2023-03-09 11:43 UTC, RuslanSlobodian commented on lab1/lab1/src/Main_package/Main.java
> +    public LocalTime addAndSearchTime() {
з назви addAndSearchTime() можна чекати, що метод добавить і шукатиме час, а насправді він робить щось інше.
краща назва: getTime()

2023-03-09 11:43 UTC, RuslanSlobodian commented on lab1/lab1/src/Main_package/Main.java
> +        int timeMinute = Integer.parseInt(partsTime[1]);
Молодець, що так зробив. 
Також можна через клас DateTimeFormatter:
Scanner scanner = new Scanner(System.in);
String shippingTimeInput = scanner.nextLine();
DateTimeFormatter format = DateTimeFormatter.ofPattern("HH:mm");
LocalTime shippingTimeFinal = LocalTime.parse(shippingTimeInput, format);

2023-03-09 11:43 UTC, RuslanSlobodian commented on lab1/lab1/src/Main_package/Main.java
> +    public  void optionSearchGeneral() {
Слово option  у назвах методів є лишнім, просто пиши назву методу виходячи з того, що цей метод робить

2023-03-09 11:46 UTC, RuslanSlobodian commented
Ще пару виправлень зроби

2023-03-10 10:45 UTC, HULK0680204682 commented on lab1/lab1/src/Main_package/Main.java
> +    public  void optionSearchGeneral() {
option добавлене щоб не було путанини з назвами.. але трошки зміню всетаки

2023-03-13 08:36 UTC, RuslanSlobodian commented on lab1/lab1/src/Main_package/Main.java
> +    public  void optionSearchGeneral() {
добавляти слово method в назві методі є лишнім, відразу починай назву методу із дієслова

2023-03-13 08:41 UTC, RuslanSlobodian approved these changes
Ще є пару нюансів, наприклад: назва об'єкта s, слово method у назві методу.
Але переходимо до наступної роботи

2023-03-13 08:43 UTC, RuslanSlobodian commented
Можеш зливати гілку, зелена кнопка Merge pull request.

2023-03-13 17:43 UTC, merged