Lab2
HULK0680204682/OOPLabs pull request #2
Opened 2023-03-15 16:58 UTC by HULK0680204682

2023-03-15 19:26 UTC, RuslanSlobodian requested changes

2023-03-15 19:26 UTC, RuslanSlobodian commented on Lab2/src/Variant10.java
> +    public static void main(String[] args) {
Розділи код з main на декілька методів, які будуть робити якусь конкретну задачу,
це полегшить читання коду і подальше використання класу.
можна вхідний текст та параметри винести у атрибути класу

2023-03-15 19:26 UTC, RuslanSlobodian commented on Lab2/src/Main.java
> +    }
В даному класі створи об'єкт класу Variant10 і з його допомогою проведи операції над текстом

2023-03-15 19:26 UTC, RuslanSlobodian commented on Lab2/src/Variant10.java
> +    public static void main(String[] args) {
https://uk.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF_%C2%ABKISS%C2%BB

2023-03-15 19:26 UTC, RuslanSlobodian commented on Lab2/src/Variant10.java
> +    public static void main(String[] args) {
https://habr.com/ru/post/424051/

2023-03-15 19:26 UTC, RuslanSlobodian commented on Lab2/src/Variant10.java
> +    public static void main(String[] args) {
https://habr.com/ru/post/485118/

2023-03-15 19:26 UTC, RuslanSlobodian commented on Lab2/src/Variant10.java
> +    public static void main(String[] args) {
А краще читати не конспект книги, а всю книгу (першу половину книги) Чистий код. Роберт Мартін 
[(https://fabulabook.com/author/robert-martin-1055.html)](https://fabulabook.com/info-chystyj-kod-7391.html)

2023-04-13 09:55 UTC, RuslanSlobodian approved these changes, later dismissed

2023-04-13 10:46 UTC, RuslanSlobodian approved these changes
Приблизно такого результату я чекав

2023-04-13 10:46 UTC, RuslanSlobodian commented on Lab2/src/Main.java
> +    public static StringBuffer text = new StringBuffer("Ввести текст, що_містить_пару спеціальних символів, які ( вводяться наприклад, дужки ) та або зірочки");
Атрибути класу повинні бути закритими private

2023-04-13 10:46 UTC, RuslanSlobodian commented on Lab2/src/Main.java
> +    public static int wordCount = 0;;
Атрибути класу повинні бути закритими private

2023-04-13 10:46 UTC, RuslanSlobodian commented on Lab2/src/Main.java
> +    public static int initialIndex = text.indexOf("(");
Атрибути класу повинні бути закритими private

2023-04-13 10:46 UTC, RuslanSlobodian commented on Lab2/src/Main.java
> +    public static  int endIndex = text.indexOf(")");
Атрибути класу повинні бути закритими private

2023-04-13 10:46 UTC, RuslanSlobodian commented on Lab2/src/Variant10.java
> +        Main.text.delete(Main.initialIndex, Main.endIndex);
Для чого користуватись атрибутами із класу Main?
можна було б передати вихідні параметри в конструктор класу Variant10, або параметрами статичного методу

2023-04-13 10:47 UTC, RuslanSlobodian approved these changes

2023-04-13 10:50 UTC, RuslanSlobodian commented
Зроби ще один коміт і новий пул ріквест, бо я всій коміт не можу ревювити

2023-04-13 11:56 UTC, RuslanSlobodian approved these changes

2023-04-14 15:01 UTC, HULK0680204682 commented
> Зроби ще один коміт і новий пул ріквест, бо я весь коміт не можу ревювити
не моду запушити коміт.. хіба якщо видалю цей запит

2023-04-20 11:09 UTC, closed without merging